### ISSUE TITLE
基础使用报错。

### ISSUE THREAD

**Issue by sansanshow** [best-flutter/flutter_swiper#13]
code
```
new Container(
    height: 120.0,
    child: new Swiper(
      itemBuilder: (BuildContext context,int index){
        return new Image.network("http://img.jandan.net/news/2018/09/2d5ff15b73f85dbd9ff302b9d4f85d4b.jpg", fit: BoxFit.fill,);
      },
      itemCount: 3,
      pagination: new SwiperPagination(),
      control: new SwiperControl(),
    ),
  );
```

错误信息（error）:

I/flutter ( 1831): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1831): The following NoSuchMethodError was thrown building AnimatedBuilder(animation:
I/flutter ( 1831): PageController#fda49(one client, offset 384000000000.0), dirty, state: _AnimatedState#b0c65):
I/flutter ( 1831): No top-level method 'Transform.scale' declared.
I/flutter ( 1831): Receiver: top-level
I/flutter ( 1831): Tried calling: Transform.scale(scale: 1.0, child: Instance of 'Image')
I/flutter ( 1831):
I/flutter ( 1831): When the exception was thrown, this was the stack:
I/flutter ( 1831): #0      _NoneloopPageViewState._buildAnimationItem.<anonymous closure> (package:flutter_swiper/src/swiper.dart)
I/flutter ( 1831): #1      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:634:12)
I/flutter ( 1831): #2      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:97:48)
I/flutter ( 1831): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3722:27)
I/flutter ( 1831): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3634:15)
I/flutter ( 1831): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 1831): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 1831): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3761:11)
I/flutter ( 1831): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 1831): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 1831): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 1831): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4646:14)
I/flutter ( 1831): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 1831): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 1831): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 1831): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 1831): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 1831): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 1831): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 1831): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)
I/flutter ( 1831): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3645:16)
I/flutter ( 1831): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3487:5)
I/flutter ( 1831): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3614:5)
I/flutter ( 1831): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3609:5)
I/flutter ( 1831): #24     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3947:11)
I/flutter ( 1831): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2899:14)
I/flutter ( 1831): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2702:12)

**Comment by Lavan01** [comment]
I think it's an issue of setting the size of the child (image). transform.scale happens before the child is even painted. The issue would probably the **missing width** of the image, since it takes time to load it from internet.

Regards,
Lavan
