### ISSUE TITLE
_positions.isNotEmpty

### ISSUE THREAD

**Issue by gxg-886** [best-flutter/flutter_swiper#166]
When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
#3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:202:41)
#4      _TransformerPageViewState.didUpdateWidget (package:transformer_page_view/transformer_page_view.dart:527:25)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)

**Comment by gxg-886** [comment]
Flutter 1.12.13+hotfix.5

**Comment by tschiekdev** [comment]
I have the same problem. The error happens to me accidentally. It is very annoying.

**Comment by lathiyaviral-avinashi** [comment]
I have the same problem. I have try to add **key: GlobalKey()** for Swiper and it's work fine for me.

**Comment by dlavrenuek** [comment]
I have this problem when setting the `index` property on `Swiper()`. The only solution that works for me is to omit `index`, pass a controller and call `controller.move(index, animation: false);`

```dart

final _controller = SwiperController();
_controller.move(index, animation: false);
//...

Swiper(controller: _controller /* ... */);
```

**Comment by wenxy** [comment]
add a controller, fixed.

 final _controller = SwiperController();
 Swiper(
          controller: _controller,
....
