### ISSUE TITLE
error and can't swipe and white while init

### ISSUE THREAD

**Issue by krmao** [best-flutter/flutter_swiper#19]
```
[ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (29329): NoSuchMethodError: The method '>' was called on null.
E/flutter (29329): Receiver: null
E/flutter (29329): Tried calling: >(411428571428.5715)
E/flutter (29329): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
E/flutter (29329): #1      double.< (dart:core/runtime/libdouble.dart:65:18)
E/flutter (29329): #2      double.<= (dart:core/runtime/libdouble.dart:78:37)
E/flutter (29329): #3      PageScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/page_view.dart:366:45)
E/flutter (29329): #4      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:147:43)
E/flutter (29329): #5      DrivenScrollActivity._end (package:flutter/src/widgets/scroll_activity.dart:634:15)
E/flutter (29329): #6      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter (29329): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter (29329): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter (29329): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter (29329): #10     Future._completeWithValue (dart:async/future_impl.dart:486:5)
E/flutter (29329): #11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
E/flutter (29329): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (29329): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter (29329): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/chatty  (29329): uid=10517(com.yimaguquan) 2.ui identical 17 lines
I/flutter (29329): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.8.3, on Mac OS X 10.12.6 16G29, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
[✓] Connected devices (1 available)

• No issues found!

```

**Comment by krmao** [comment]
```
E/flutter ( 2284): Tried calling: >(411428571428.5715)
E/flutter ( 2284): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
E/flutter ( 2284): #1      double.< (dart:core/runtime/libdouble.dart:65:18)
E/flutter ( 2284): #2      double.<= (dart:core/runtime/libdouble.dart:78:37)
E/flutter ( 2284): #3      PageScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/page_view.dart:366:45)
E/flutter ( 2284): #4      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:147:43)
E/flutter ( 2284): #5      DrivenScrollActivity._end (package:flutter/src/widgets/scroll_activity.dart:634:15)
E/flutter ( 2284): #6      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter ( 2284): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter ( 2284): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter ( 2284): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter ( 2284): #10     Future._completeWithValue (dart:async/future_impl.dart:486:5)
E/flutter ( 2284): #11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
E/flutter ( 2284): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2284): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter ( 2284): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/chatty  ( 2284): uid=10521(com.yimaguquan) 4.ui identical 17 lines
I/flutter ( 2284): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
E/flutter ( 2284): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 2284): NoSuchMethodError: The method '>' was called on null.
E/flutter ( 2284): Receiver: null
E/flutter ( 2284): Tried calling: >(411428571428.5715)
E/flutter ( 2284): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
E/flutter ( 2284): #1      double.< (dart:core/runtime/libdouble.dart:65:18)
E/flutter ( 2284): #2      double.<= (dart:core/runtime/libdouble.dart:78:37)
E/flutter ( 2284): #3      PageScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/page_view.dart:366:45)
E/flutter ( 2284): #4      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:147:43)
E/flutter ( 2284): #5      DrivenScrollActivity._end (package:flutter/src/widgets/scroll_activity.dart:634:15)
E/flutter ( 2284): #6      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter ( 2284): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter ( 2284): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter ( 2284): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter ( 2284): #10     Future._completeWithValue (dart:async/future_impl.dart:486:5)
E/flutter ( 2284): #11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
E/flutter ( 2284): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2284): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
I/flutter ( 2284): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/chatty  ( 2284): uid=10521(com.yimaguquan) 4.ui identical 17 lines
I/flutter ( 2284): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
E/flutter ( 2284): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 2284): NoSuchMethodError: The method '>' was called on null.
E/flutter ( 2284): Receiver: null
E/flutter ( 2284): Tried calling: >(411428571428.5715)
E/flutter ( 2284): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
E/flutter ( 2284): #1      double.< (dart:core/runtime/libdouble.dart:65:18)
E/flutter ( 2284): #2      double.<= (dart:core/runtime/libdouble.dart:78:37)
E/flutter ( 2284): #3      PageScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/page_view.dart:366:45)
E/flutter ( 2284): #4      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:147:43)
E/flutter ( 2284): #5      DrivenScrollActivity._end (package:flutter/src/widgets/scroll_activity.dart:634:15)
E/flutter ( 2284): #6      _RootZone.run (dart:async/zone.dart:1374:54)
E/flutter ( 2284): #7      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:153:18)
E/flutter ( 2284): #8      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:612:39)
E/flutter ( 2284): #9      Future._propagateToListeners (dart:async/future_impl.dart:668:37)
E/flutter ( 2284): #10     Future._completeWithValue (dart:async/future_impl.dart:486:5)
E/flutter ( 2284): #11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
E/flutter ( 2284): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 2284): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by krmao** [comment]
```
E/flutter ( 4245): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 4245): NoSuchMethodError: The getter 'visible' was called on null.
E/flutter ( 4245): Receiver: null
E/flutter ( 4245): Tried calling: visible
E/flutter ( 4245): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
E/flutter ( 4245): #1      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:572:26)
E/flutter ( 4245): #2      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #4      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #5      RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2780:37)
E/flutter ( 4245): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #9      RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:164:19)
E/flutter ( 4245): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #13     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #15     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #17     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:500:18)
E/flutter ( 4245): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #20     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #21     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2250:17)
E/flutter ( 4245): #22     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:595:12)
E/flutter ( 4245): #23     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:117:19)
E/flutter ( 4245): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #26     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:20)
E/flutter ( 4245): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #28     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2250:17)
E/flutter ( 4245): #29     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:595:12)
E/flutter ( 4245): #30     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #31     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2250:17)
E/flutter ( 4245): #32     RenderFlex.hitTestChildren (package:flutter/src/rendering/flex.dart:925:12)
E/flutter ( 4245): #33     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1924:11)
E/flutter ( 4245): #34     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultHitTestChildren (package:flutter/src/rendering/box.dart:2250:17)
E/flutter ( 4245): #35     RenderStack.hitTestChildren (package:flutter/src/rendering/stack.dart:595:12)
E/flutter ( 4245): #

```

**Comment by krmao** [comment]
看来原因是因为 初始化数量为 0
可以先用一个空的Container 或者 ImageView 替代
```
new Container(
              alignment: Alignment.center,
              child: new AspectRatio(
                aspectRatio: 2.0,
                child: bannerList?.length == 0
                    ? CommonWidgetManager.getNetworkImageWidget(null)
                    : new Swiper(
                        itemBuilder: (BuildContext context, int index) {
                          var imageUrl = bannerList[index]["image"];
                          return CommonWidgetManager.getNetworkImageWidget(imageUrl);
                        },
                        itemCount: bannerList.length,
                        pagination: new SwiperPagination(builder: DotSwiperPaginationBuilder(activeColor: Colors.red, color: Colors.white)),
                        control: new SwiperControl(iconPrevious: null, iconNext: null),
                        controller: new SwiperController(),
                        autoplay: true,
                        autoplayDelay: 3000,
                        autoplayDisableOnInteraction: true,
                      ),
              ),
            )
```
这样就好了, 只是如果itemCount==0的情况考虑到 Swiper 空间里面就完美了, 不然还要如上修改, 否则不能滑动, 各种报错.

**Comment by jzoom** [comment]
哦，对，这个一开始考虑了，后面升级了版本没有考虑到，下个版本修复下
