### ISSUE TITLE
Exception thrown on latest Flutter master

### ISSUE THREAD

**Issue by Zazo032** [best-flutter/flutter_swiper#227]
This is the output from logs:

```
I/flutter (13956): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13956): The following _CastError was thrown building PageIndicator(dirty, state: _PageIndicatorState#1ec88):
I/flutter (13956): Null check operator used on a null value
I/flutter (13956): 
I/flutter (13956): The relevant error-causing widget was:
I/flutter (13956):   PageIndicator
I/flutter (13956):   file:///<elided>/pub.dartlang.org/flutter_swiper-1.1.6/lib/src/swiper_pagination.dart:188:18
I/flutter (13956): 
I/flutter (13956): When the exception was thrown, this was the stack:
I/flutter (13956): #0      ScrollPosition.maxScrollExtent (package:flutter/src/widgets/scroll_position.dart:141:49)
I/flutter (13956): #1      TransformerPageController.realPage (package:transformer_page_view/transformer_page_view.dart:148:18)
I/flutter (13956): #2      TransformerPageController.page (package:transformer_page_view/transformer_page_view.dart:179:11)
I/flutter (13956): #3      _PageIndicatorState._createPainer (package:flutter_page_indicator/flutter_page_indicator.dart:235:39)
I/flutter (13956): #4      _PageIndicatorState.build (package:flutter_page_indicator/flutter_page_indicator.dart:259:18)
I/flutter (13956): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4758:27)
I/flutter (13956): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4641:15)
I/flutter (13956): #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4813:11)
I/flutter (13956): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4335:5)
I/flutter (13956): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4620:5)
I/flutter (13956): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4804:11)
I/flutter (13956): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4615:5)
I/flutter (13956): ...     Normal element mounting (13 frames)
I/flutter (13956): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (13956): #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6248:32)
I/flutter (13956): ...     Normal element mounting (15 frames)
I/flutter (13956): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (13956): #41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6248:32)
I/flutter (13956): ...     Normal element mounting (31 frames)
I/flutter (13956): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (13956): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3346:18)
I/flutter (13956): #74     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:138:18)
I/flutter (13956): #75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2696:19)
I/flutter (13956): #76     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118:12)
I/flutter (13956): #77     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1883:59)
I/flutter (13956): #78     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
I/flutter (13956): #79     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1883:14)
I/flutter (13956): #80     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:227:7)
I/flutter (13956): #81     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:353:5)
I/flutter (13956): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #83     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
I/flutter (13956): #84     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
I/flutter (13956): #85     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
I/flutter (13956): #86     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
I/flutter (13956): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #91     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1306:11)
I/flutter (13956): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #106    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #123    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #124    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3220:13)
I/flutter (13956): #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #126    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #127    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #128    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:714:15)
I/flutter (13956): #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #130    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #132    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #133    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #134    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #140    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (13956): #141    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (13956): #142    RenderView.performLayout (package:flutter/src/rendering/view.dart:167:14)
I/flutter (13956): #143    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (13956): #144    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (13956): #145    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:435:19)
I/flutter (13956): #146    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:907:13)
I/flutter (13956): #147    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:301:5)
I/flutter (13956): #148    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (13956): #149    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (13956): #150    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (13956): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (13956): 
I/flutter (13956): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by patelpathik** [comment]
Is there any alternative to suppress this issue for a while ? I'm facing same issue on `flutter Channel stable, 2.0.5`
I have to share apk for preview, TIA!
