### ISSUE TITLE
锤子手机OD103报错

### ISSUE THREAD

**Issue by luyouxin** [best-flutter/flutter_swiper#98]
锤子手机第一次安装的时候报错，但是热重载以后就能正常显示，同样的代码在华为手机上是正常的
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building NotificationListener<ScrollNotification>:
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 110 pos 12: '_positions.isNotEmpty'
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
#3      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:120:41)
#4      _TransformerPageViewState.didUpdateWidget (package:transformer_page_view/transformer_page_view.dart:527:25)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3975:58)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#11     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4697:32)
#12     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5088:17)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#16     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#18     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#22     StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#26     StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#34     StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#37     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#38     ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#42     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#48     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
#49     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1113:34)
#50     Iterable.forEach (dart:core/iterable.dart:277:30)
#51     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1139:24)
#52     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1084:7)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#56     ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#60     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4697:32)
#61     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5088:17)
#62     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#68     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#70     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#74     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#80     ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#92     StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#96     StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#104    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#108    StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#112    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#116    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#118    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4697:32)
#119    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5088:17)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#123    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#127    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#131    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#137    StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#139    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#142    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#143    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#147    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#151    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#155    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#159    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#164    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#165    StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#166    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#167    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#168    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#169    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#171    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#173    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#176    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#177    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#180    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#181    StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#182    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#184    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#185    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#187    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#190    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#191    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#192    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#194    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#198    StatefulElement.update (package:flutter/src/widgets/framework.dart:3990:5)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#202    StatelessElement.update (package:flutter/src/widgets/framework.dart:3892:5)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#204    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4979:14)
#205    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#207    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#208    ProxyElement.update (package:flutter/src/widgets/framework.dart:4102:5)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:2844:15)
#210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3846:16)
#211    Element.rebuild (package:flutter/src/widgets/framework.dart:3656:5)
#212    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2314:33)
#213    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
#214    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
#215    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
#216    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
#217    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
#221    _invoke (dart:ui/hooks.dart:220:10)
#222    _drawFrame (dart:ui/hooks.dart:178:3)
(elided 5 frames from class _AssertionError and package dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by davidkIXI2** [comment]
hi i have same ,

**Comment by mario202k** [comment]
I found the solution!!
Your Swiper must be wrap with StreamBuilder or something that rebuild more than once Swiper.
In my case,
`StreamBuilder( stream: slides, initialData: [], builder: (context, AsyncSnapshot snap) { List slideList = snap.data.toList(); return slideList.isNotEmpty ? Swiper( itemBuilder: (BuildContext context, int index) { return Image.network( slideList[index]['image'], fit: BoxFit.fill, ); },`
Check the slideList not empty.
